// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ixyqxyqwmxtqftaaippo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml4eXF4eXF3bXh0cWZ0YWFpcHBvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQwNTg0OTgsImV4cCI6MjA2OTYzNDQ5OH0.VMy7hml8VyIERwHbMaBX7ClvPuimYtGZZmNp4ZkB4iw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});